create table order_book(
    id INteger primary key generated by default AS IDENTITY,
    book_id int,
    order_id int,
    quantity int,
    total_price int,
    FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);